/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteRouteImport } from './routes/_shell/route'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellSettingsRouteImport } from './routes/_shell/settings'
import { Route as ShellDashboardRouteImport } from './routes/_shell/dashboard'
import { Route as ShellConnectionsRouteImport } from './routes/_shell/connections'
import { Route as ShellUserIndexRouteImport } from './routes/_shell/user.index'
import { Route as ShellDocsIndexRouteImport } from './routes/_shell/docs.index'
import { Route as ShellDashboardIndexRouteImport } from './routes/_shell/dashboard.index'
import { Route as ShellDocsSlugRouteImport } from './routes/_shell/docs.$slug'
import { Route as ShellChatNewRouteImport } from './routes/_shell/chat.new'
import { Route as ShellChatConversationIdRouteImport } from './routes/_shell/chat.$conversationId'
import { Route as ShellWorkspaceWorkspaceIdSettingsRouteImport } from './routes/_shell/workspace.$workspaceId.settings'
import { Route as ShellDashboardPagePageIdRouteImport } from './routes/_shell/dashboard.page.$pageId'

const ShellRouteRoute = ShellRouteRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellConnectionsRoute = ShellConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellUserIndexRoute = ShellUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellDocsIndexRoute = ShellDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellDashboardIndexRoute = ShellDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellDashboardRoute,
} as any)
const ShellDocsSlugRoute = ShellDocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellChatNewRoute = ShellChatNewRouteImport.update({
  id: '/chat/new',
  path: '/chat/new',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellChatConversationIdRoute = ShellChatConversationIdRouteImport.update({
  id: '/chat/$conversationId',
  path: '/chat/$conversationId',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellWorkspaceWorkspaceIdSettingsRoute =
  ShellWorkspaceWorkspaceIdSettingsRouteImport.update({
    id: '/workspace/$workspaceId/settings',
    path: '/workspace/$workspaceId/settings',
    getParentRoute: () => ShellRouteRoute,
  } as any)
const ShellDashboardPagePageIdRoute =
  ShellDashboardPagePageIdRouteImport.update({
    id: '/page/$pageId',
    path: '/page/$pageId',
    getParentRoute: () => ShellDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/connections': typeof ShellConnectionsRoute
  '/dashboard': typeof ShellDashboardRouteWithChildren
  '/settings': typeof ShellSettingsRoute
  '/chat/$conversationId': typeof ShellChatConversationIdRoute
  '/chat/new': typeof ShellChatNewRoute
  '/docs/$slug': typeof ShellDocsSlugRoute
  '/dashboard/': typeof ShellDashboardIndexRoute
  '/docs/': typeof ShellDocsIndexRoute
  '/user/': typeof ShellUserIndexRoute
  '/dashboard/page/$pageId': typeof ShellDashboardPagePageIdRoute
  '/workspace/$workspaceId/settings': typeof ShellWorkspaceWorkspaceIdSettingsRoute
}
export interface FileRoutesByTo {
  '/connections': typeof ShellConnectionsRoute
  '/settings': typeof ShellSettingsRoute
  '/': typeof ShellIndexRoute
  '/chat/$conversationId': typeof ShellChatConversationIdRoute
  '/chat/new': typeof ShellChatNewRoute
  '/docs/$slug': typeof ShellDocsSlugRoute
  '/dashboard': typeof ShellDashboardIndexRoute
  '/docs': typeof ShellDocsIndexRoute
  '/user': typeof ShellUserIndexRoute
  '/dashboard/page/$pageId': typeof ShellDashboardPagePageIdRoute
  '/workspace/$workspaceId/settings': typeof ShellWorkspaceWorkspaceIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteRouteWithChildren
  '/_shell/connections': typeof ShellConnectionsRoute
  '/_shell/dashboard': typeof ShellDashboardRouteWithChildren
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/chat/$conversationId': typeof ShellChatConversationIdRoute
  '/_shell/chat/new': typeof ShellChatNewRoute
  '/_shell/docs/$slug': typeof ShellDocsSlugRoute
  '/_shell/dashboard/': typeof ShellDashboardIndexRoute
  '/_shell/docs/': typeof ShellDocsIndexRoute
  '/_shell/user/': typeof ShellUserIndexRoute
  '/_shell/dashboard/page/$pageId': typeof ShellDashboardPagePageIdRoute
  '/_shell/workspace/$workspaceId/settings': typeof ShellWorkspaceWorkspaceIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connections'
    | '/dashboard'
    | '/settings'
    | '/chat/$conversationId'
    | '/chat/new'
    | '/docs/$slug'
    | '/dashboard/'
    | '/docs/'
    | '/user/'
    | '/dashboard/page/$pageId'
    | '/workspace/$workspaceId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/connections'
    | '/settings'
    | '/'
    | '/chat/$conversationId'
    | '/chat/new'
    | '/docs/$slug'
    | '/dashboard'
    | '/docs'
    | '/user'
    | '/dashboard/page/$pageId'
    | '/workspace/$workspaceId/settings'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/connections'
    | '/_shell/dashboard'
    | '/_shell/settings'
    | '/_shell/'
    | '/_shell/chat/$conversationId'
    | '/_shell/chat/new'
    | '/_shell/docs/$slug'
    | '/_shell/dashboard/'
    | '/_shell/docs/'
    | '/_shell/user/'
    | '/_shell/dashboard/page/$pageId'
    | '/_shell/workspace/$workspaceId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRouteRoute: typeof ShellRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/connections': {
      id: '/_shell/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ShellConnectionsRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/user/': {
      id: '/_shell/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof ShellUserIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/docs/': {
      id: '/_shell/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof ShellDocsIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/dashboard/': {
      id: '/_shell/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ShellDashboardIndexRouteImport
      parentRoute: typeof ShellDashboardRoute
    }
    '/_shell/docs/$slug': {
      id: '/_shell/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof ShellDocsSlugRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/chat/new': {
      id: '/_shell/chat/new'
      path: '/chat/new'
      fullPath: '/chat/new'
      preLoaderRoute: typeof ShellChatNewRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/chat/$conversationId': {
      id: '/_shell/chat/$conversationId'
      path: '/chat/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof ShellChatConversationIdRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/workspace/$workspaceId/settings': {
      id: '/_shell/workspace/$workspaceId/settings'
      path: '/workspace/$workspaceId/settings'
      fullPath: '/workspace/$workspaceId/settings'
      preLoaderRoute: typeof ShellWorkspaceWorkspaceIdSettingsRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/dashboard/page/$pageId': {
      id: '/_shell/dashboard/page/$pageId'
      path: '/page/$pageId'
      fullPath: '/dashboard/page/$pageId'
      preLoaderRoute: typeof ShellDashboardPagePageIdRouteImport
      parentRoute: typeof ShellDashboardRoute
    }
  }
}

interface ShellDashboardRouteChildren {
  ShellDashboardIndexRoute: typeof ShellDashboardIndexRoute
  ShellDashboardPagePageIdRoute: typeof ShellDashboardPagePageIdRoute
}

const ShellDashboardRouteChildren: ShellDashboardRouteChildren = {
  ShellDashboardIndexRoute: ShellDashboardIndexRoute,
  ShellDashboardPagePageIdRoute: ShellDashboardPagePageIdRoute,
}

const ShellDashboardRouteWithChildren = ShellDashboardRoute._addFileChildren(
  ShellDashboardRouteChildren,
)

interface ShellRouteRouteChildren {
  ShellConnectionsRoute: typeof ShellConnectionsRoute
  ShellDashboardRoute: typeof ShellDashboardRouteWithChildren
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellChatConversationIdRoute: typeof ShellChatConversationIdRoute
  ShellChatNewRoute: typeof ShellChatNewRoute
  ShellDocsSlugRoute: typeof ShellDocsSlugRoute
  ShellDocsIndexRoute: typeof ShellDocsIndexRoute
  ShellUserIndexRoute: typeof ShellUserIndexRoute
  ShellWorkspaceWorkspaceIdSettingsRoute: typeof ShellWorkspaceWorkspaceIdSettingsRoute
}

const ShellRouteRouteChildren: ShellRouteRouteChildren = {
  ShellConnectionsRoute: ShellConnectionsRoute,
  ShellDashboardRoute: ShellDashboardRouteWithChildren,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellChatConversationIdRoute: ShellChatConversationIdRoute,
  ShellChatNewRoute: ShellChatNewRoute,
  ShellDocsSlugRoute: ShellDocsSlugRoute,
  ShellDocsIndexRoute: ShellDocsIndexRoute,
  ShellUserIndexRoute: ShellUserIndexRoute,
  ShellWorkspaceWorkspaceIdSettingsRoute:
    ShellWorkspaceWorkspaceIdSettingsRoute,
}

const ShellRouteRouteWithChildren = ShellRouteRoute._addFileChildren(
  ShellRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ShellRouteRoute: ShellRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
